# Generated by Django 5.2.4 on 2025-08-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('manager', 'Manager'), ('developer', 'Developer'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BACKEND', 'Back-end'), ('FRONTEND', 'Front-end'), ('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=20),
        ),
    ]
